local Library = loadstring(readfile("MacOSLibrary/main.lua"))()
local Window = Library:Init("Example", true, Enum.KeyCode.LeftControl, true)
Window:Divider("Main Tabs")
local Sec = Window:Section("Main Section", "home")
Sec:Divider("Elements")
Sec:Label("This is a label.")
Sec:Paragraph("Paragraph", "This is a paragraph with more detailed information.")
Sec:Button("Primary Button", function()
    print("Primary Button clicked!")
end)
Sec:Button("Destructive Button", function()
    print("Destructive Button clicked!")
end, true)
Sec:Switch("Switch", false, function(state)
    print("Switch is now: ", state)
end)
Sec:TextField("Text Field", "Placeholder...", function(text)
    print("Text entered: ", text)
end)
Sec:Slider("Slider", 0, 100, 50, function(value)
    print("Slider value: ", value)
end)
Sec:Dropdown("Dropdown", {"Option 1", "Option 2", "Option 3"}, "Option 1", function(selected)
    print("Dropdown selected: ", selected)
end)
Sec:MultiDropdown("Multi Dropdown", {"Apples", "Bananas", "Cherries"}, {"Apples"}, function(selectedTable)
    print("Multi Dropdown selected: ", table.concat(selectedTable, ", "))
end)
Sec:ColorPicker("Colorpicker", Color3.fromRGB(255, 0, 0), function(color)
    print("Color selected: ", color)
end)
Sec:Keybind("Keybind", Enum.KeyCode.E, function()
    print("Keybind pressed!")
end)
Window:Divider("Other")
local NotifSec = Window:Section("Notifications", "bell")
NotifSec:Button("Temp Notification", function()
    Window:TempNotify("Example", "This is a temporary notification.", "bell")
end)
NotifSec:Button("Notification 1", function()
    Window:Notify("Notify 1", "This is a notification with one button.", "Okay", "info")
end)
NotifSec:Button("Notification 2", function()
    Window:Notify2("Notify 2", "This is a notification with two buttons.", "Yes", "No", "warning")
end)